### PR TITLE
1.1.6

### LINKED ISSUE #16: Neck dislocation
Friend's neck dislocates when I get close

List of other installed mods:
- Achievements+
- Colour Cameras
- Common Camera Utilities
- Custom Ship Log Mode
- Cut Achievements
- Daydream
- Enable Meditation 
- General Enhancements 
- Global SSR
- Glowstick Bracelets
- Hug Mod
- Immersion 
- Menu Framework 
- New Horizons 
- Proud Hearthians 
- Quality of Life Features
- Quantum Moon Orbit Line
- Reactive Hearthians 
- Secret Settings
- Ship Light Toggle
- Signals+
- Silly Filters 
- Suit Log
- Vanilla Fix
- Voice Acting Mod

### LINKED ISSUE #19: Outsider ship logs appear in New Horizons custom systems
Should be a simple fix, just an if statement before the logs are created that checks if NH is installed and if it has sent the player to a new system

### PR DESCRIPTION
**Pull request by xen-42**
Fixed ship logs appearing in New Horizons custom systems and compatibility fix with Daydream (Fixes #19, fixes #16)

### CODE REVIEW

**Review by TRSasasusu — APPROVED** [review]
@xen-42 The neck thing is no problem. I checked it with and without daydream.

I found a problem with the ship log in New Horizons custom system, specifically Archipelago (NOT archipelago randomizer.)
After warping to the Archipelago system, opening the ship log raises exceptions.
I checked Evacuation and Unnamed Mystery are no problems, so I think no ship log in Archipelago causes this phenomenon.
Such a star system is rare, so we could ignore the issue, and I approved this PR.

**Comment by xen-42** [comment]
@TRSasasusu thanks. When warping to Archipelago system, do the exceptions appear to actually break anything in the game or do they have no effect?

**Comment by TRSasasusu** [comment]
@xen-42 In Archipelago system, after opening the ship log, you cannot move anymore.
image

**Comment by xen-42** [comment]
Turns out that is just an NH bug and not related to the outsider (uh oh) so I will merge this (I got the same issue without Outsider installed)

**Comment by TRSasasusu** [comment]
I didn't check Archipelago without the outsider. Thanks.

**Pull request merged**
